# Generated by Django 3.0.4 on 2022-07-30 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='base.Category', verbose_name='カテゴリー'),
            preserve_default=False,
        ),
    ]
